### ISSUE TITLE
Dont know how to handle message type 15

### ISSUE THREAD

**Issue by cabrerachaparro** [uunicorn/python-validity#10]
Hello,
I am getting the following message when running pair.py

```
Initializing flash...
Detected Flash IC: W25Q80B, 1048576 bytes
Traceback (most recent call last):
  File "pair.py", line 27, in <module>
    init_flash()
  File "/home/dcabrera/python-validity/validitysensor/init_flash.py", line 141, in init_flash
    tls.open()
  File "/home/dcabrera/python-validity/validitysensor/tls.py", line 133, in open
    self.parse_tls_response(rsp)
  File "/home/dcabrera/python-validity/validitysensor/tls.py", line 349, in parse_tls_response
    raise Exception('Dont know how to handle message type %02x' % t)
Exception: Dont know how to handle message type 15
```
Any idea what is wrong?

**OS:** Fedora 32
**Hardware:** T480
**Device:** Bus 001 Device 016: ID 06cb:009a Synaptics, Inc.

**Comment by cabrerachaparro** [comment]
Sorry, I was using wrong driver.
