### ISSUE TITLE
Incompatibility with newer python system libraries

### ISSUE THREAD

**Issue by VorpalBlade** [uunicorn/python-validity#112]
After recent system updates on Arch Linux the python3-validity service fails to start every time with the following error in journalctl:

```
Feb 24 19:03:45 athena dbus-service[2611]: /usr/lib/python-validity/dbus-service:33: PyGIDeprecationWarning: Since version 3.11, calling threads_init is no longer needed. See: https://wiki.gnome.org/PyGObject/Threading
Feb 24 19:03:45 athena dbus-service[2611]:   GLib.threads_init()
Feb 24 19:03:45 athena dbus-service[2611]: Traceback (most recent call last):
Feb 24 19:03:45 athena dbus-service[2611]:   File "/usr/lib/python-validity/dbus-service", line 307, in <module>
Feb 24 19:03:45 athena dbus-service[2611]:     main()
Feb 24 19:03:45 athena dbus-service[2611]:   File "/usr/lib/python-validity/dbus-service", line 245, in main
Feb 24 19:03:45 athena dbus-service[2611]:     config = yaml.load(configfd)
Feb 24 19:03:45 athena dbus-service[2611]: TypeError: load() missing 1 required positional argument: 'Loader'
Feb 24 19:03:45 athena systemd[1]: python3-validity.service: Main process exited, code=exited, status=1/FAILURE
Feb 24 19:03:45 athena systemd[1]: python3-validity.service: Failed with result 'exit-code'.
```
I have not not looked at which specific system library that caused this.

**Comment by VorpalBlade** [comment]
Investigated and discovered that this seems to have been fixed since the latest release already. Maybe it is time to make a 0.13? Closing the bug for now and switching to using the -git version of the package from AUR.
