### ISSUE TITLE
Don`t work with 27c6:5125 (Huawei MateBook 16)

### ISSUE THREAD

**Issue by pribylovkirill** [uunicorn/python-validity#142]
Could you please add support for this device?
```
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 002: ID 27c6:5125 Shenzhen Goodix Technology Co.,Ltd. 
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 003: ID 1358:c123  
Bus 001 Device 002: ID 3277:0003  
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```
```
kirill➜~» sudo systemctl stop python3-validity                                                     
kirill➜~» sudo validity-sensors-firmware                                                           [
Traceback (most recent call last):
  File "/usr/bin/validity-sensors-firmware", line 92, in <module>
    raise Exception('No supported validity device found')
Exception: No supported validity device found
kirill➜~» sudo python3 /usr/share/python-validity/playground/factory-reset.py                     
Traceback (most recent call last):
  File "/usr/share/python-validity/playground/factory-reset.py", line 5, in <module>
    usb.open()
  File "/usr/lib/python3/dist-packages/validitysensor/usb.py", line 50, in open
    self.open_dev(dev)
  File "/usr/lib/python3/dist-packages/validitysensor/usb.py", line 62, in open_dev
    raise Exception('No matching devices found')
Exception: No matching devices found
```

**Comment by tarkin88** [comment]
i'm add to this request

**Comment by bardanovk** [comment]
me too
