### ISSUE TITLE
Fingerprint sometimes can't be detected flawlesly

### ISSUE THREAD

**Issue by Anifyuli** [uunicorn/python-validity#162]
Hello, Mister.
I want to reporting Python3-Validity unexpected bug if systems using fingerprint scanner. I get it from status report `python3-validity.service`. It always give report finger not recognized
```shell
Jun 13 08:32:12 thinkpad-x280 python3[56717]: ERROR:root:Finger not recognized: 04000100db
                                              Traceback (most recent call last):
                                                File "/usr/lib/python-validity/dbus-service", line 121, in run
                                                  usrid, subtype, hsh = sensor.identify(update_cb)
                                                File "/usr/lib/python3/dist-packages/validitysensor/sensor.py", line 912, in identify
                                                  return self.match_finger()
                                                File "/usr/lib/python3/dist-packages/validitysensor/sensor.py", line 874, in match_finger
                                                  raise Exception('Finger not recognized: %s' % hexlify(b).decode())
                                              Exception: Finger not recognized: 04000100db
```

I can solve it with restarting `python3-validity` and other services depends it, such as `open-fprintd, open-fprintd-suspend`, and `open-fprintd-resume`. But, after doing that, this trouble come again with same reports. 
I wish this bug can solve soon as possible. Thanks for your contributions in open source world. Sorry my English thanks for reading my issue

My system info :
OS : Pop!_OS 22.04 based on Ubuntu 22.04
Device : Thinkpad X280
Fingerprint hardware : ID 06cb:009a Synaptics, Inc. Metallica MIS Touch Fingerprint Reader
DE : GNOME 42.5 (customized with COSMIC extensions)

**Comment by Anifyuli** [comment]
I now moved to Ubuntu 23.04 and I still get same problems
