### ISSUE TITLE
Can't install on silverblue 38

### ISSUE THREAD

**Issue by appelgriebsch** [uunicorn/python-validity#164]
After the recent merge of the PR that fixes the paths for the runtime files to be compatible with immutable filesystems I'm trying to set it up on my local silverblue 38, but it fails when running `rpm-ostree install ....` with the message that the provided fprintd-clients and fprintd-clients-pam interfere with the system provided fprintd and fprint-pam.... (the latter also having a higher build number on Silverblue 38 than the provided ones in the copr repo).

Any updates on Silverblue compatibility and installation instructions? Are the custom fprintd-clients really necessary, or can I go with the system provided ones instead?

**Comment by 4bitFox** [comment]
I managed to install it with the following Reddit thread. Add the .repo file to `/etc/yum.repos.d/`.  
Then `sudo rpm-ostree override remove fprintd fprintd-pam`
After that install the required packages with rpm-ostree.

`https://www.reddit.com/r/Fedora/comments/yynarx/this_is_how_you_can_use_copr_on_silverblue/`
`https://copr.fedorainfracloud.org/coprs/tigro/python-validity/`

I am running into the following errors tough, because of the read only filesystem...
Havn't gotten any further than this unfortunately. :-(

```
[name@thinkpad ~]$ sudo validity-sensors-firmware
Downloading https://download.lenovo.com/pccbbs/mobiles/nz3gf07w.exe to extract 6_07f_lenovo_mis_qm.xpfwext
Extracting "version 5.3.3542.26 (NZ3GF07W)" - setup data version 5.5.7 (unicode)
 - "code$GetExtractPath$/WBF_Drivers/6_07f_lenovo_mis_qm.xpfwext"
Done.
Found firmware at /tmp/tmpz1gws55y/code$GetExtractPath$/WBF_Drivers/6_07f_lenovo_mis_qm.xpfwext
Traceback (most recent call last):
  File "/usr/bin/validity-sensors-firmware", line 102, in <module>
    shutil.copy(fwpath, python_validity_data)
  File "/usr/lib64/python3.11/shutil.py", line 419, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib64/python3.11/shutil.py", line 258, in copyfile
    with open(dst, 'wb') as fdst:
         ^^^^^^^^^^^^^^^
OSError: [Errno 30] Read-only file system: '/usr/share/python-validity/6_07f_lenovo_mis_qm.xpfwext'
[name@thinkpad ~]$ fprintd-enroll 
Impossible to enroll: GDBus.Error:net.reactivated.Fprint.Error.NoSuchDevice: 

```
