### ISSUE TITLE
Systemd service python-validity get error after longtime suspend or after reboot

### ISSUE THREAD

**Issue by Anifyuli** [uunicorn/python-validity#173]
Hello, I want to report `python-validity.service` bug in Python3 exec file (I guess) and this bug repeated after resume for longtime suspend or after rebooting machine. This bug appear like this
```bash
Okt 01 10:16:54 ThinkPad-X280 python3[847]: ERROR:root:Finger not recognized: 04000100db
                                            Traceback (most recent call last):
                                              File "/usr/lib/python-validity/dbus-service", line 121, in run
                                                usrid, subtype, hsh = sensor.identify(update_cb)
                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
                                              File "/usr/lib/python3/dist-packages/validitysensor/sensor.py", line 912, in identify
                                                return self.match_finger()
                                                       ^^^^^^^^^^^^^^^^^^^
                                              File "/usr/lib/python3/dist-packages/validitysensor/sensor.py", line 874, in match_finger
                                                raise Exception('Finger not recognized: %s' % hexlify(b).decode())
                                            Exception: Finger not recognized: 04000100db
```
If I restart all service from `pyhton-validity` & `open-fprintd`, other service like `open-fprintd-resume.service` and `open-fprintd.service` because this bug. Sometime, I get other report, but I forget for report in here (because longtime suspend & resume from it). So, I'm sorry I can't attach that error in here.
I wish it can fix immediately. Thanks for your updates & hardworks.

System information :
Device : ThinkPad X280 20KEA062UK
Kernel : 6.2.0.33-generic
Distro : Ubuntu 23.04 Lunar Lobster
FP : Bus 001 Device 005: ID 06cb:009a Synaptics, Inc. Metallica MIS Touch Fingerprint Reader
Systemd : 252.5-2ubuntu3.1
Source install : download `.deb` from PPA for Kinetic Kudu

**Comment by YovanggaAnandhika** [comment]
@Anifyuli solutions and explanations that can be tried https://github.com/uunicorn/python-validity/issues/128#issuecomment-2437045697
