### ISSUE TITLE
Trace dump on finger recognition but still seems to work?

### ISSUE THREAD

**Issue by ixnewton** [uunicorn/python-validity#207]
Is there anything that can be done to fix this?

I have re-installed open-fprintd, libfprint-tod and python-validity to be sure that all is up to date. It looks like validitysensor/usb.py, core.py, libusb1.py are not happy. 

`05/12/2024 19:42	kscreenlocker_greet	Failed to write to the pipe: Invalid argument.
05/12/2024 19:42	ERROR:root	Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/validitysensor/usb.py", line 128, in wait_int
    resp = self.dev.read(131, 1024, timeout=100)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/usb/core.py", line 1029, in read
    ret = fn(
          ^^^
  File "/usr/lib/python3.12/site-packages/usb/backend/libusb1.py", line 864, in intr_read
    return self.__read(self.lib.libusb_interrupt_transfer,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/usb/backend/libusb1.py", line 954, in __read
    _check(retval)
  File "/usr/lib/python3.12/site-packages/usb/backend/libusb1.py", line 602, in _check
    raise USBTimeoutError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBTimeoutError: [Errno 110] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python-validity/dbus-service", line 121, in run
    usrid, subtype, hsh = sensor.identify(update_cb)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/validitysensor/sensor.py", line 906, in identify
    raise e
  File "/usr/lib/python3.12/site-packages/validitysensor/sensor.py", line 900, in identify
    self.capture(CaptureMode.IDENTIFY)
  File "/usr/lib/python3.12/site-packages/validitysensor/sensor.py", line 705, in capture
    b = usb.wait_int()
        ^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/validitysensor/usb.py", line 135, in wait_int
    raise CancelledException()
validitysensor.usb.CancelledException
`

**Comment by ixnewton** [comment]
Making sure suspend/resume services are enabled with: systemctl enable open-fprintd-resume open-fprintd-suspend seems to have resolved this! Though some updates arrived today which may have played a part. Closing for now!
