### ISSUE TITLE
[fedora] after suspending or hibernating service stops bringing functionalities

### ISSUE THREAD

**Issue by bwiercinski** [uunicorn/python-validity#61]
1. `fprintd-verify` works. i'm checking the timestamp of the last log visible in `sudo systemctl status python3-validity.service`
2. `systemctl suspend`, no new logs visible because of that
3. `fprintd-verify`:
```
Using device /net/reactivated/Fprint/Device/6
ListEnrolledFingers failed: Traceback (most recent call last):
  File "/usr/lib64/python3.9/site-packages/dbus/service.py", line 711, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/python-validity/dbus-service", line 90, in ListEnrolledFingers
    raise e
  File "/usr/lib/python-validity/dbus-service", line 81, in ListEnrolledFingers
    usr = self.user2record(user)
  File "/usr/lib/python-validity/dbus-service", line 64, in user2record
    return db.lookup_user(self.user2identity(user))
  File "/usr/lib/python3.9/site-packages/validitysensor/db.py", line 163, in lookup_user
    stg = self.get_user_storage(name='StgWindsor')
  File "/usr/lib/python3.9/site-packages/validitysensor/db.py", line 149, in get_user_storage
    return parse_user_storage(tls.cmd(pack('<BHH', 0x4b, dbid, len(name)) + name))
  File "/usr/lib/python3.9/site-packages/validitysensor/tls.py", line 122, in cmd
    rsp = self.app(cmd)
  File "/usr/lib/python3.9/site-packages/validitysensor/tls.py", line 152, in app
    return self.parse_tls_response(self.usb.cmd(self.make_app_data(b)))
  File "/usr/lib/python3.9/site-packages/validitysensor/tls.py", line 351, in parse_tls_response
    raise Exception('Unexpected TLS version %d %d' % (mj, mn))
Exception: Unexpected TLS version 4 0
```
4. the service is still active!!
5. `sudo systemctl restart python3-validity.service`
6. works again :o
i'm running Fedora 33. i had to change permission of a driver and pre-initialize some files: https://github.com/uunicorn/python-validity/issues/54#issuecomment-742575505

i think i'm ok with stopping the service after suspending, and starting it again after waking up the laptop, but i dont know is it possible on linux on the systemctl level

**Comment by bwiercinski** [comment]
sorry this is duplicate of https://github.com/uunicorn/python-validity/issues/59

solution from there works. consider to add this in readme ;)

regards
