### ISSUE TITLE
not support lenovo xiaoxin air 2020

### ISSUE THREAD

**Issue by zzugyl** [uunicorn/python-validity#62]
In my case:
`Bus 003 Device 003: ID 04f3:0c4d Elan Microelectronics Corp. ELAN:Fingerprint`

env:
`Ubuntu 20.04.1 LTS`

run:
```
~ fprintd-enroll   
list_devices failed:   
```
and:
```
validity-sensors-firmware                       
Traceback (most recent call last):
  File "/usr/bin/validity-sensors-firmware", line 92, in <module>
    raise Exception('No supported validity device found')
Exception: No supported validity device found
```

**Comment by himekifee** [comment]
This is a validity sensor project, not a elan one.

**Comment by Aadityakaushik** [comment]
> In my case: `Bus 003 Device 003: ID 04f3:0c4d Elan Microelectronics Corp. ELAN:Fingerprint`
> 
> env: `Ubuntu 20.04.1 LTS`
> 
> run:
> 
> ```
> ~ fprintd-enroll   
> list_devices failed:   
> ```
> 
> and:
> 
> ```
> validity-sensors-firmware                       
> Traceback (most recent call last):
>   File "/usr/bin/validity-sensors-firmware", line 92, in <module>
>     raise Exception('No supported validity device found')
> Exception: No supported validity device found
> ```

have you found a solution if yes please help me i am also facing same problem
