### ISSUE TITLE
Is there any way to make it work on linux mint cinnamon?

### ISSUE THREAD

**Issue by Majk720** [uunicorn/python-validity#99]
I did the tutorial for ubuntu, no errors but i have no log in option via fingerprint in accounts section in settings :(

**Comment by nnelas** [comment]
Hi @Majk720 ,

I tried to configure python-validity on my Linux Mint 20.2 and I haven't found any issue. 

Just a couple of notes here:
1) You should enroll your finger with `fprintd-enroll`. Be patience and place your finger multiple times onto your reader until you see an "enroll success". If you keep receiving "enroll failed" errors, try to follow [this](https://github.com/uunicorn/python-validity#errors-on-startup), at least it worked for me.
2) Make sure fingerprint authentication is enabled with `sudo pam-auth-update`
3) Logout and try to login. Fingerprint auth should be now required to login.

Let me know if these worked for you.

**Comment by ryangwsimmons** [comment]
@Majk720 All versions of Linux Mint (apart from the clearly labelled "Debian Edition") are based on Ubuntu. Because of this, you should be able to follow the Ubuntu instructions without issue. Once everything is installed, you should be able to follow the instructions given above. If you have any issues, or if there's anything you don't understand, just ask. We were all noobs at one point.

**Comment by Majk720** [comment]
so ok, i removed fprintd, installed everything using the tutorial on github but when i type "fprintd-enroll" i get the message that fprintd is not installed and i can install it but i removed it in the first step

**Comment by ryangwsimmons** [comment]
@Majk720 did you try running `fprintd-enroll` with `sudo`? If I recall correctly, it needs superuser to work.

**Comment by Majk720** [comment]
@ryangwsimmons no, it is not working, i don't know why it is asking me to install fprintd when i have installed open fprintd

**Comment by ryangwsimmons** [comment]
@Majk720 can you provide the output of `sudo apt install open-fprintd fprintd-clients python3-validity` on your computer? An easy way to do this is to run `sudo apt install open-fprintd fprintd-clients python3-validity > output.txt`, then copy the contents of the text file it creates here. To make it easier to read, put the contents of the text file between 3 backticks (the \` character), so your comment would look like this:

\`\`\`
\<the contents of the output from the text file\>
\`\`\`

From what you're saying, it sounds to me like the installation of `open-fprintd` wasn't successful, for whatever reason. If I have the output of that command, it might help in determining what exactly is going wrong.

**Comment by Majk720** [comment]
@ryangwsimmons when i run this output.txt command i get a warning `WARNING: apt does not have a stable CLI interface. Use with caution in scripts`

**Comment by ryangwsimmons** [comment]
@Majk720 is that the only output? That's to be expected, and it's true, but not really relevant in these circumstances. If there's other output, please post it here. You can ignore the warning.

**Comment by Majk720** [comment]
'sudo apt install open-fprintd fprintd-clients python3-validity
Czytanie list pakietów... Gotowe
Budowanie drzewa zależności       
Odczyt informacji o stanie... Gotowe
fprintd-clients is already the newest version (1.90.1-1ubuntu3).
The following additional packages will be installed:
  innoextract libboost-filesystem1.67.0 libboost-iostreams1.67.0
  libboost-program-options1.67.0 libboost-system1.67.0 python3-usb
Zostaną zainstalowane następujące NOWE pakiety:
  innoextract libboost-filesystem1.67.0 libboost-iostreams1.67.0
  libboost-program-options1.67.0 libboost-system1.67.0 open-fprintd python3-usb
  python3-validity
0 aktualizowanych, 8 nowo instalowanych, 0 usuwanych i 1 nieaktualizowanych.
Konieczne pobranie 1 307 kB archiwów.
Po tej operacji zostanie dodatkowo użyte 10,4 MB miejsca na dysku.
Kontynuować? [T/n] t
Pobieranie:1 http://ftp.agh.edu.pl/ubuntu focal/universe amd64 libboost-system1.67.0 amd64 1.67.0-17ubuntu8 [204 kB]
Pobieranie:2 http://ppa.launchpad.net/uunicorn/open-fprintd/ubuntu focal/main amd64 open-fprintd all 0.6~ppa1 [6 916 B]
Pobieranie:3 http://ppa.launchpad.net/uunicorn/open-fprintd/ubuntu focal/main amd64 python3-validity all 0.13~ppa1 [74,3 kB]
Pobieranie:4 http://ftp.agh.edu.pl/ubuntu focal/universe amd64 libboost-filesystem1.67.0 amd64 1.67.0-17ubuntu8 [234 kB]
Pobieranie:5 http://ftp.agh.edu.pl/ubuntu focal/universe amd64 libboost-iostreams1.67.0 amd64 1.67.0-17ubuntu8 [224 kB]
Pobieranie:6 http://ftp.agh.edu.pl/ubuntu focal/universe amd64 libboost-program-options1.67.0 amd64 1.67.0-17ubuntu8 [331 kB]
Pobieranie:7 http://ftp.agh.edu.pl/ubuntu focal/universe amd64 python3-usb all 1.0.2-1build1 [37,6 kB]
Pobieranie:8 http://ftp.agh.edu.pl/ubuntu focal/universe amd64 innoextract amd64 1.8-1 [195 kB]
Pobrano 1 307 kB w 1s (1 468 kB/s) 
Wybieranie wcześniej niewybranego pakietu libboost-system1.67.0:amd64.
(Odczytywanie bazy danych ... 585336 plików i katalogów obecnie zainstalowanych.)
Przygotowywanie do rozpakowania pakietu .../0-libboost-system1.67.0_1.67.0-17ubuntu8_amd64
.deb ...
Rozpakowywanie pakietu libboost-system1.67.0:amd64 (1.67.0-17ubuntu8) ...
Wybieranie wcześniej niewybranego pakietu libboost-filesystem1.67.0:amd64.
Przygotowywanie do rozpakowania pakietu .../1-libboost-filesystem1.67.0_1.67.0-17ubuntu8_a
md64.deb ...
Rozpakowywanie pakietu libboost-filesystem1.67.0:amd64 (1.67.0-17ubuntu8) ...
Wybieranie wcześniej niewybranego pakietu libboost-iostreams1.67.0:amd64.
Przygotowywanie do rozpakowania pakietu .../2-libboost-iostreams1.67.0_1.67.0-17ubuntu8_am
d64.deb ...
Rozpakowywanie pakietu libboost-iostreams1.67.0:amd64 (1.67.0-17ubuntu8) ...
Wybieranie wcześniej niewybranego pakietu libboost-program-options1.67.0:amd64.
Przygotowywanie do rozpakowania pakietu .../3-libboost-program-options1.67.0_1.67.0-17ubun
tu8_amd64.deb ...
Rozpakowywanie pakietu libboost-program-options1.67.0:amd64 (1.67.0-17ubuntu8) ...
Wybieranie wcześniej niewybranego pakietu open-fprintd.
Przygotowywanie do rozpakowania pakietu .../4-open-fprintd_0.6~ppa1_all.deb ...
Rozpakowywanie pakietu open-fprintd (0.6~ppa1) ...
Wybieranie wcześniej niewybranego pakietu python3-usb.
Przygotowywanie do rozpakowania pakietu .../5-python3-usb_1.0.2-1build1_all.deb ...
Rozpakowywanie pakietu python3-usb (1.0.2-1build1) ...
Wybieranie wcześniej niewybranego pakietu innoextract.
Przygotowywanie do rozpakowania pakietu .../6-innoextract_1.8-1_amd64.deb ...
Rozpakowywanie pakietu innoextract (1.8-1) ...
Wybieranie wcześniej niewybranego pakietu python3-validity.
Przygotowywanie do rozpakowania pakietu .../7-python3-validity_0.13~ppa1_all.deb ...
Rozpakowywanie pakietu python3-validity (0.13~ppa1) ...
Konfigurowanie pakietu libboost-program-options1.67.0:amd64 (1.67.0-17ubuntu8) ...
Konfigurowanie pakietu python3-usb (1.0.2-1build1) ...
Konfigurowanie pakietu libboost-iostreams1.67.0:amd64 (1.67.0-17ubuntu8) ...
Konfigurowanie pakietu open-fprintd (0.6~ppa1) ...
Konfigurowanie pakietu libboost-system1.67.0:amd64 (1.67.0-17ubuntu8) ...
Konfigurowanie pakietu libboost-filesystem1.67.0:amd64 (1.67.0-17ubuntu8) ...
Konfigurowanie pakietu innoextract (1.8-1) ...
Konfigurowanie pakietu python3-validity (0.13~ppa1) ...
Traceback (most recent call last):
  File "/usr/bin/validity-sensors-firmware", line 92, in <module>
    raise Exception('No supported validity device found')
Exception: No supported validity device found
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepth
ook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_bin_validity-sens
ors-firmware.0.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/validity-sensors-firmware", line 92, in <module>
    raise Exception('No supported validity device found')
Exception: No supported validity device found
Przetwarzanie wyzwalaczy pakietu man-db (2.9.1-1)...
Przetwarzanie wyzwalaczy pakietu dbus (1.12.16-2ubuntu2.1)...
Przetwarzanie wyzwalaczy pakietu libc-bin (2.31-0ubuntu9.2)...'
The language is polish

**Comment by ryangwsimmons** [comment]
@Majk720 are you sure that your fingerprint reader is supported by this driver? What model of computer do you have? Where did you find this repo?

```
Exception: No supported validity device found
```
This message indicates that a supported fingerprint reader was not found on your system. The installation aborted, that's why it wasn't working when you tried to enroll a finger before.

**Comment by Semiire** [comment]
when I tried 'fprintd-enroll', I got a response 'list devices failed'
